implementing retention policy for project versions artifacts
finos/legend-depot pull request #282
Opened 2023-05-15 10:35 UTC by gs-gunjan

implementing retention policy for project versions artifacts

2023-05-16 12:59 UTC, elopezcastro requested changes
please see and action comments

2023-05-16 12:59 UTC, elopezcastro commented on legend-depot-core-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java
> +    public List<StoreProjectVersionData> findBranchSnapshotVersions(String groupId, String artifactId)
please dont chnage this method, let the caller decide if it needs master or not

2023-05-16 12:59 UTC, elopezcastro commented on legend-depot-artifacts-purge/src/main/java/org/finos/legend/depot/store/artifacts/purge/services/ArtifactsPurgeServiceImpl.java
> +        evictProjectVersions.parallelStream().forEach(pv -> evict(pv.getGroupId(), pv.getArtifactId(), pv.getVersionId()));
there no lots of info message here how do oyu know things are being done

2023-05-16 12:59 UTC, elopezcastro commented on legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/services/ProjectVersionRefreshHandler.java
> +        if (projects.findBranchSnapshotVersions(event.getGroupId(), event.getArtifactId()).size() >= maximumSnapshotsAllowed)
please roll this back..number of snaphots includes master

2023-05-17 06:29 UTC, gs-gunjan commented on legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/configuration/ArtifactsRetentionPolicyConfiguration.java
> +    private int maximumSnapshotsAllowed = 5;
because this can be changes, from the config, we just assign it a default

2023-05-17 09:55 UTC, elopezcastro requested changes

2023-05-17 09:55 UTC, elopezcastro commented on legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/configuration/ArtifactsRetentionPolicyConfiguration.java
> +    private int maximumSnapshotsAllowed = 5;
you doing that for the below so be consistent.. they can be overriden by config.
they should be called something like default  ,look at max retries or queue confog for examples

2023-05-17 09:55 UTC, elopezcastro commented on legend-depot-store-api/src/main/java/org/finos/legend/depot/store/admin/api/metrics/QueryMetricsStore.java
> +    List<VersionQueryMetric> findLeastRecentlyUsed(String regexPattern, Date date);
this is not really doing least recently used ....is a filter by date.. findMetricsBefore ,. would be a better name
also can you think of a way to exclude esnapsho the regex is not areally good way to spwecify the search..
whats the method doing...finding version metrics before date or finding snapshot metrics before  a date

2023-05-17 09:55 UTC, elopezcastro commented on legend-depot-store-metrics/src/main/java/org/finos/legend/depot/store/metrics/services/QueryMetricsHandler.java
> +        return metricsStore.findLeastRecentlyUsed(".*\\..*\\..*", date);
this implementation is not going to scale very well plus the intention of the method is not what the name does.. as per my comment above.

2023-05-17 09:55 UTC, elopezcastro commented on legend-depot-store-mongo/src/main/java/org/finos/legend/depot/store/mongo/admin/metrics/QueryMetricsMongo.java
> +        return find(and(regex(VERSION_ID, regexPattern),lte("lastQueryTime", date.getTime())));
regrex does not perform very well

2023-05-17 14:02 UTC, gs-gunjan commented on legend-depot-artifacts-refresh/src/main/java/org/finos/legend/depot/store/artifacts/configuration/ArtifactsRetentionPolicyConfiguration.java
> +    private static final int ONE_MONTH = 30;
done

2023-05-17 14:18 UTC, elopezcastro submitted a review, later dismissed

2023-05-17 14:33 UTC, merged