Storing latest version to project data
finos/legend-depot pull request #409
Opened 2023-10-20 13:36 UTC by gs-gunjan

Storing latest version to project data
Removing the pagination of projects data

2023-10-24 10:30 UTC, elopezcastro requested changes

2023-10-24 10:30 UTC, elopezcastro commented on legend-depot-artifacts-services/src/main/java/org/finos/legend/depot/services/artifacts/refresh/ProjectVersionRefreshHandler.java
> +                projectData.setLatestVersion(versionId);
this code is a dup bellow. you can make more readable by splitting the calculation of what latest version shoudl be and then doing the actual set/update

2023-10-25 06:03 UTC, gs-gunjan commented on legend-depot-entities-services/src/main/java/org/finos/legend/depot/services/entities/EntityClassifierServiceImpl.java
> +    private List<ProjectVersion> getLatestProjectVersionByPage(int page, int pageSize, List<StoreProjectData> allProjects)
I don't think we have tests for this code

2023-10-25 06:05 UTC, gs-gunjan commented on legend-depot-core-data-services/src/main/java/org/finos/legend/depot/services/projects/ProjectsServiceImpl.java
> +            return Optional.empty();
We should, but our pattern has been returning optional empty

2023-10-30 14:44 UTC, elopezcastro approved these changes

2023-10-30 16:16 UTC, elopezcastro approved these changes

2023-10-30 16:16 UTC, merged